networks:
  lan_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.172.10.0/24

services:
  dns:
    # Using official Ubuntu/Debian bind9 image instead of the problematic one
    image: ubuntu/bind9:latest
    container_name: dns_equipo7
    volumes:
      - ./dns/named.conf:/etc/bind/named.conf
      - ./dns/zones:/etc/bind/zones
    ports:
      - "8053:53/udp"
      - "8053:53/tcp"
    networks:
      dmz_net:
        ipv4_address: 10.172.10.11

  web:
    image: nginx
    container_name: web_equipo7
    volumes:
      - ./web:/usr/share/nginx/html
      - ./ftp_files:/usr/share/nginx/html/archivos
      - ./web/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8080:80"
    networks:
      dmz_net:
        ipv4_address: 10.172.10.12      

  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: ftp_equipo7
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "alex"
      FTP_USER_PASS: "alex"
      FTP_USER_HOME: "/home/ftpusers/usuario"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      dmz_net:
        ipv4_address: 10.172.10.13
    volumes:
      - ./ftp_files:/home/ftpusers/usuario    

  samba:
    image: dperson/samba
    container_name: samba_equipo7
    command: '-u "equipo7;1234" -s "archivos;/shared;yes;no"'
    volumes:
      - ./samba:/shared
    ports:
      - "139:139"
      - "445:445"
    networks:
      lan_net:
        ipv4_address: 192.168.10.20

  db_server:
    image: mysql:latest
    container_name: db_server
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    networks:
      lan_net:
        ipv4_address: 192.168.10.21
    restart: always

  cliente:
    image: debian
    container_name: cliente_equipo7
    stdin_open: true
    tty: true
    command: bash
    networks:
      lan_net:
        ipv4_address: 192.168.10.100